import video from "../assets/videos/video1.mp4";
import image1 from "../assets/ArchitecturalProjects/RENDER POSTAGEM 4.jpg";
import image2 from "../assets/ArchitecturalProjects/RENDER POSTAGEM 5.jpg";
import image3 from "../assets/ArchitecturalProjects/render total.jpg";

export const cards = [
  {
    id: 1,
    image: image1,
    title: "Casa Monte Mor",
    location: "Recife, PE",
    vertical: true,
    video,
  },
  {
    id: 2,
    image: image2,
    title: "Casa Campinas",
    location: "Recife, PE",
    vertical: false,
  },
  {
    id: 3,
    image: image1,
    title: "Casa Vinhedo",
    location: "Recife, PE",
    vertical: false,
  },
  {
    id: 4,
    image: image3,
    title: "Casa Campos do Jordão",
    location: "Recife, PE",
    vertical: false,
  },
  {
    id: 5,
    image: image2,
    title: "Teatro Boas Artes",
    location: "Recife, PE",
    vertical: false,
  },
  {
    id: 6,
    image: image1,
    title: "Teatro São Paulo",
    location: "Recife, PE",
    vertical: true,
    video,
  },
  {
    id: 7,
    image: image2,
    title: "Concerto Bela Guanabara",
    location: "Recife, PE",
    vertical: true,
  },
  {
    id: 8,
    image: image3,
    title: "Monumental de São Paulo",
    location: "Recife, PE",
    vertical: false,
  },
  {
    id: 9,
    image: image1,
    title: "Aparecida de Goiânia",
    location: "Recife, PE",
    vertical: false,
  },
  {
    id: 10,
    image: image2,
    title: "Pedreira de São Gonçalo",
    location: "Recife, PE",
    vertical: true,
    video,
  },
  {
    id: 11,
    image: image3,
    title: "Monte de Vilas Boas",
    location: "Recife, PE",
    vertical: false,
  },
  {
    id: 12,
    image: image1,
    title: "Card 1",
    location: "Recife, PE",
    vertical: false,
  },
  {
    id: 13,
    image: image2,
    title: "Concerto de Piracicaba",
    location: "Recife, PE",
    vertical: false,
  },
  {
    id: 14,
    image: image3,
    title: "Cordilheiras de Manreza",
    location: "Recife, PE",
    vertical: false,
  },
  {
    id: 15,
    image: image1,
    title: "Casa de Maringá",
    location: "Recife, PE",
    vertical: true,
  },
];
